#!/bin/sh /etc/rc.common
# 
# Copyright 2019 BD7MQB <bd7mqb@qq.com>
# This is free software, licensed under the GNU GENERAL PUBLIC LICENSE, Version 2.0
# 

START=91
APP=YSFGateway
USE_PROCD=1
LOG_PATH=/var/log/mmdvm

start_service() {
    [ -d $LOG_PATH ] || mkdir -m 0775 -p $LOG_PATH
    ubus -t 60 wait_for network.interface network.wireless 2>/dev/null

    echo "Starting $APP Service..."
    procd_open_instance
    procd_set_param respawn
    procd_set_param command /usr/sbin/$APP
    procd_close_instance
}
 
stop_service() {
    echo "Stoping $APP Service..."
}