#!/bin/sh /etc/rc.common

START=99
APP=YSFParrot
USE_PROCD=1
LOG_PATH=/var/log/mmdvm
PORT=42012

start_service() {
    [ -d $LOG_PATH ] || mkdir -m 0775 -p $LOG_PATH
    ubus -t 60 wait_for network.interface network.wireless 2>/dev/null

    echo "Starting $APP Service..."
    procd_open_instance
    procd_set_param respawn
    procd_set_param command /usr/sbin/$APP $PORT
    procd_close_instance
}
 
stop_service() {
    echo "Stoping $APP Service..."
}