#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.
 
START=99
APP=P25Parrot
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
PORT=42011
 
start() {
    ubus -t 60 wait_for network.interface network.wireless 2>/dev/null
    service_start /usr/sbin/$APP $PORT
}
 
stop() {
    service_stop /usr/sbin/$APP
}